name: Run PR Checks
on: pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Unit Tests
        uses: burrunan/gradle-cache-action@v1
        with:
          gradle-version: wrapper
          arguments: detekt
          properties: |
            org.gradle.vfs.watch=false
            org.gradle.vfs.verbose=false
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Unit Tests
        uses: burrunan/gradle-cache-action@v1
        with:
          gradle-version: wrapper
          arguments: test
          properties: |
            org.gradle.vfs.watch=false
            org.gradle.vfs.verbose=false
