name: Publish to GitHub Packages
on:
  push:
    branches: [ main ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'
      - name: Publish to GitHub Packages
        uses: burrunan/gradle-cache-action@v1
        with:
          gradle-version: wrapper
          arguments: publishAllPublicationsToGithubPackagesRepository
          properties: |
            org.gradle.vfs.watch=false
            org.gradle.vfs.verbose=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}