name: Publish to GitHub Packages
on:
  release:
    types:
      - prereleased
      - released
env:
  GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
  GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
jobs:
  publish-to-gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Publish Plugins to Gradle
        uses: burrunan/gradle-cache-action@v1
        with:
          gradle-version: wrapper
          arguments: publishPlugins
          properties: |
            release=true
            gradle.publish.key=$GRADLE_PUBLISH_KEY
            gradle.publish.secret=$GRADLE_PUBLISH_SECRET
            org.gradle.vfs.watch=false
            org.gradle.vfs.verbose=false
